export const ADMIN_DASHBOARD_TABS = [
  {
    id: 'users',
    label: 'Users',
    description: 'Manage users and profiles',
    path: '/users',
    permission: 'admin_tab_users',
  },
  {
    id: 'payouts',
    label: 'Payouts',
    description: 'Review and manage payout requests',
    path: '/payouts',
    permission: 'admin_tab_payouts',
  },
  {
    id: 'ledger',
    label: 'Ledger',
    description: 'View account ledger entries',
    path: '/ledger',
    permission: 'admin_tab_ledger',
  },
  {
    id: 'trade-history',
    label: 'Trade History',
    description: 'View historical orders and trades',
    path: '/trade-history',
    permission: 'admin_tab_trade_history',
  },
  {
    id: 'pandl',
    label: 'P&L',
    description: 'Analyze profit and loss',
    path: '/pandl',
    permission: 'admin_tab_pnl',
  },
  {
    id: 'positions-mis',
    label: 'P.MIS',
    description: 'MIS positions view',
    path: '/trade/all-positions',
    permission: 'admin_tab_positions_mis',
  },
  {
    id: 'positions-normal',
    label: 'P.Normal',
    description: 'Normal positions view',
    path: '/all-positions-normal',
    permission: 'admin_tab_positions_normal',
  },
  {
    id: 'positions-userwise',
    label: 'P.Userwise',
    description: 'Userwise positions view',
    path: '/all-positions-userwise',
    permission: 'admin_tab_positions_userwise',
  },
  {
    id: 'payin',
    label: 'Payin',
    description: 'View and manage payin transactions',
    path: '/dashboard?tab=payin',
    permission: 'admin_tab_payin',
  },
  {
    id: 'detailed-logs',
    label: 'Detailed Logs',
    description: 'Access detailed system and activity logs',
    path: '/dashboard?tab=detailedLogs',
    permission: 'admin_tab_detailed_logs',
  },
  {
    id: 'sms-otp-settings',
    label: 'SMS OTP Settings',
    description: 'Configure SMS OTP provider settings',
    path: '/dashboard?tab=smsOtp',
    permission: 'admin_tab_sms_otp_settings',
  },
  {
    id: 'course-enrollments',
    label: 'Course Enrollments',
    description: 'Manage user course enrollments',
    path: '/dashboard?tab=courseEnrollments',
    permission: 'admin_tab_course_enrollments',
  },
  {
    id: 'user-signups',
    label: 'User Signups',
    description: 'Review and manage new user signups',
    path: '/dashboard?tab=userSignups',
    permission: 'admin_tab_user_signups',
  },
];

export const ADMIN_TAB_PERMISSION_KEYS = ADMIN_DASHBOARD_TABS.map((tab) => tab.permission);
